### ISSUE TITLE
Simplify test dataset for paired data

### ISSUE THREAD

**Issue by Brennan1994** [HenryGeorgist/fda-model#30]
Figure out how to bring it down to mental math calculations

**Comment by HenryGeorgist** [comment]
static double[] x = new double[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        static double[] y = new double[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        static double[] y2 = new double[] { 2, 4, 6, 8, 10, 12, 14, 16, 18, 20};
when you use f(1) you expect to get 1, when you use f(1.5) you expect 1.5,
when you compose x,y with x,y2 you should be able to calculate the expectation

**Comment by HenryGeorgist** [comment]
i think the stage flow probability stuff is great for testing ead.Simulation.Compute()
