### ISSUE TITLE
Integration specific to probability

### ISSUE THREAD

**Issue by Brennan1994** [HenryGeorgist/fda-model#33]
https://github.com/HenryGeorgist/fda-model/blob/c55c301a8e427209bcac45c34c86c503650c95e7/fda-model/paireddata/PairedData.cs#L103

This IF condition in the integrate function makes this integration proprietary to functions with xVals of probability. How can we organize ourselves so this isn't an option for paired data representing a rating curve (stage-flow)?

**Comment by HenryGeorgist** [comment]
Add an optional min and max to the iintegrate interface.  Set max and min to the max and min of xvals if not pecified. When you call with probabilities specify min of 0 and max of 1

**Comment by Brennan1994** [comment]
another option is to leave it as is, because in FDA, there is never a reason to integrate something other than damage probability to achieve EAD. With that in mind, I'll leave this as it is until I have a reason to change it.
